services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    develop:
      watch:
        - path: .
          target: /app
          action: sync
        - path: .
          action: rebuild
